### ISSUE TITLE
Eliminate discussion of differences between Python 2 and Python 3 in day1

### ISSUE THREAD

**Issue by bburan** [dasaderi/python_neurobootcamp#12]
As suggested, I would just mention that there are some key differences between Python 2 and Python 3 and that students need to make sure they're working with Python 3 when writing code.

**Comment by laderast** [comment]
I agree with this.

**Comment by dasaderi** [comment]
I agree with this as well. However, I'm going to leave the two mentions of the main differences just in case someone will ever encounter Python 2. Also I use this as excuse to introduce them to "import...".

**Comment by lakarstens** [comment]
I am making this change. I think the two mentions are a little confusing in the day 1 notebook, so I have made a separate notebook discussing the differences and how to identify which version of python you are using. I reference this in the Day 1 materials. (I think this would fit as an additional reference on Day 5). I will add a different example of import if we think they need to learn import on day 1.

**Comment by dasaderi** [comment]
I also have made some changes to the notebook. I'll push soon. Thanks Lisa!

**Comment by lakarstens** [comment]
The discussion about Python 2 and Python 3 has been minimized in the Day 1 notebook and the more lengthy discussion has been moved to Day 5 as an additional notebook.
