### ISSUE TITLE
Decide what to do on Day #5

### ISSUE THREAD

**Issue by dasaderi** [dasaderi/python_neurobootcamp#2]
We have not yet defined what it will happen on Day #5. @bburan proposed we leave it open to questions from the students. I think that is a good idea, but we might need to have it a bit structured. 

For instance, we could ask students to bring in their own data (if they have it) and help them load into a notebook where they could do some simple manipulations. If students don't have datasets, they can pair up or form small groups. 

More/better ideas?

**Comment by svdavid** [comment]
Some basic statistical analysis. Like how to do a t-test or ANOVA? Given the short timeframe of the class, I'm concerned that the students aren't going to have a lot of time to develop their own problem.

I could adapt the first part of my lab on linear regression. To make it challenging, we could give the students a mystery data set where they have to identify some signal?

**Comment by dasaderi** [comment]
@svdavid, I think that's a good idea!

**Comment by laderast** [comment]
I think this could be good, but we'd have to make it really do-able by everyone. 

We did say that day 5 is evaluation and installing python, so whether students pass/fail is partly dependent on this.

**Comment by bburan** [comment]
If we have them do ANOVA, maybe better to just jump to GLMMs? Then we can introduce the statsmodels package.

However, I think any sort of statistics above and beyond a t-test will require some introduction. Probably more than the time available after getting Python installed on their computers.

**Comment by svdavid** [comment]
Good point that we should keep it simple. Maybe installing python and executing a t-test is enough. 

... At the same time, if the goal is to get the students to install python, maybe we should start that on day 1. like a homework assignment? That way the "advanced" students could work independently on notebooks running on their own machines.

**Comment by laderast** [comment]
We talked about doing installs on day 1. We decided on doing the installs on day 5 since the students will probably be more motivated to do it on the last day.

If there are people who want to install it on the first day after class, someone should support them because it isn't always easy to get it up and running.
