### ISSUE TITLE
Finalize syllabus by December 14

### ISSUE THREAD

**Issue by dasaderi** [dasaderi/python_neurobootcamp#3]
We need to provide students who enroll with a syllabus. Ted and I drafted one, but it needs more polishing. Please take a look at it [here](https://github.com/dasaderi/python_neurobootcamp/blob/master/syllabus.md).
Thanks!

**Comment by laderast** [comment]
I will contact Jackie for sections to make syllabus official

**Comment by dasaderi** [comment]
Hey @laderast do you need help writing the syllabus? What can I do?

**Comment by laderast** [comment]
Jackie gave us the sections for syllabus. She included directions on what to add in the email. Do you mind doing this and checking in a pdf into the repo?

**Comment by dasaderi** [comment]
Sure, will do it tomorrow. 💯

**Comment by laderast** [comment]
Awesome, thanks!
