### ISSUE TITLE
Day 5 - Skeletal Notebook

### ISSUE THREAD

**Issue by laderast** [dasaderi/python_neurobootcamp#8]
General task for final evaluation:

1. Take a folder full of files (either different electrophys files, or stats for different dyes for imaging)
2. Load files and combine them into a single DataFrame
3. Do aggregate measure across experiment (i.e., average intensity for each file, to look for batch effects).

Ted to do:
1. Start day 5 folder and simple outline for the files

Lisa to do: 
1. Copy installation notes to day 5 folder

**Comment by lakarstens** [comment]
I added the installation notes. It directs the students to the download page for anaconda and helps them figure out how to navigate to anaconda/jupyter notebooks on their own computer. This is altered from my course documents - we had issues with students getting very confused with the online documentation for checking the installation (and also used this to introduce them to jupyter notebooks in general- I took a lot of that text out). 

Someone should review this for content.

**Comment by laderast** [comment]
I will take a look today
